version: "3.8"
services:
  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
    command: >
      -m "tech tech tech tech tech"
      --chain.networkId 1337
      --db /data
      --host 0.0.0.0
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - ganache
    environment:
      - WEB3_PROVIDER=http://ganache:8545

